spring.application.name=backend
server.port=8081
# ==========================================
# CONEXIÓN A LA BASE DE DATOS POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/utilities_db
spring.datasource.username=postgres
spring.datasource.password=juanda0915
# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE (El ORM)
# ==========================================
# 'update' le dice a Spring que cree o modifique las tablas automáticamente 
# basándose en tus clases Java, sin borrar los datos existentes.
spring.jpa.hibernate.ddl-auto=update

# Esto imprimirá en la consola el código SQL que Spring genera por detrás. 
# Te servirá muchísimo para entender qué está pasando y para documentar tu proyecto.
spring.jpa.show-sql=true

# Le indicamos el dialecto exacto para que optimice las consultas para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Buena práctica de rendimiento para APIs REST
spring.jpa.open-in-view=false